
name: Build and Test Template
run-name: Build and Test Project Template

on:
  pull_request:
    branches:    
      - master

jobs:
  Build-And-Test-Template:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # This is nescessary so it does not conflict with git-version

      - name: Run cake step
        uses: cake-build/cake-action@v1
        with:
          script-path: build.cake
          target: BuildAndTest

      - name: Publish Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: TestedLibrary Artifacts
          path: ./artifacts/